apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    env: dev
  name: argo-workflows
  namespace: argocd
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/apps/argo_workflows/base
    repoURL: https://github.com/k203007/argo-workflow-demo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    retry:
      limit: 4
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m0s
