resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-workflows/v3.4.3/manifests/quick-start-minimal.yaml
 
patchesStrategicMerge:
  - workflow-configmap.yaml

images:
  - name: quay.io/argoproj/argocli
    newTag: v3.4.3

namespace: argo
