# ClusterRole to define permissions
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-resources-01
rules:
  - apiGroups:
      - "*"
    resources:
      - cronjobs
      - pods
      - services
      - deployments
      - statefulsets
      - daemonsets
      - jobs
      - configmaps
      - persistentvolumeclaims
      - ingresses
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
